# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcINAuRCmVrcxZM_b8oZi9r04CbbajdG
"""

# ===============================
# SMART INCIDENT DETECTION AI AGENT
# USING YOLOv8 (GOOGLE COLAB)
# ===============================

# Install required libraries
!pip install ultralytics opencv-python-headless

# Import libraries
from ultralytics import YOLO
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Load YOLOv8 model (pre-trained)
model = YOLO("yolov8n.pt")

# Upload video file
from google.colab import files
uploaded = files.upload()

# Get video file name
video_path = list(uploaded.keys())[0]

# Open video
cap = cv2.VideoCapture(video_path)

prev_vehicle_count = 0
incident_detected = False
frame_count = 0

print("🚦 Smart Incident Detection Started...")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1

    # Run YOLOv8 detection
    results = model(frame)

    # Count vehicles (car, bus, truck, bike)
    vehicle_count = 0
    for cls in results[0].boxes.cls:
        if int(cls) in [2, 3, 5, 7]:  # car, motorbike, bus, truck
            vehicle_count += 1

    # Simple incident logic (sudden drop in vehicles)
    if prev_vehicle_count > 0 and vehicle_count < prev_vehicle_count - 2:
        incident_detected = True
        cv2.putText(frame, "⚠ INCIDENT DETECTED", (50, 50),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

    prev_vehicle_count = vehicle_count

    # Draw detection boxes
    annotated_frame = results[0].plot()

    # Show every 10th frame (to avoid lag)
    if frame_count % 10 == 0:
        cv2_imshow(annotated_frame)

    # Stop after incident detection (optional)
    if incident_detected:
        print("🚨 INCIDENT ALERT GENERATED!")
        break

cap.release()
print("✅ Video Processing Completed")